import localFont from "next/font/local";
import { headers } from "next/headers";
import "./globals.css"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Ian Filmes - Login",
  description: "Generated by create next app",
};

//pegando o url do middleware
const headersList = await headers()
const header_url = headersList.get('x-url') || 'http://localhost:3000/'
export const urlpath = header_url.substring(21)

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
