import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "Ian Filmes - Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <main>
      <Nav/>
      {children}
    </main>
  );
}
