import Nav from "@/components/Nav";

export const metadata = {
  title: "Ian Filmes - Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <main className="pt-16">
      <Nav/>
      {children}
    </main>
  );
}
